openapi: 3.0.0
paths:
  /auth/sign-up:
    post:
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
      responses:
        '201':
          description: ''
      tags:
        - auth
  /auth/sign-in:
    post:
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInDto'
      responses:
        '200':
          description: ''
      tags:
        - auth
  /auth/sign-out:
    post:
      operationId: AuthController_signOut
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - auth
  /auth/session:
    get:
      operationId: AuthController_getSessionInfo
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSessionInfoDto'
      tags:
        - auth
  /account:
    get:
      operationId: AccountController_getAccount
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountDto'
      tags:
        - account
    patch:
      operationId: AccountController_patchAccount
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchAccountDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountDto'
      tags:
        - account
  /block-list:
    get:
      operationId: BlockListController_getList
      parameters:
        - name: q
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockListDto'
      tags:
        - block-list
  /block-list/item:
    post:
      operationId: BlockListController_addBlockItem
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddBlockItemDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockListDto'
      tags:
        - block-list
  /block-list/item/{id}:
    delete:
      operationId: BlockListController_removeBlockItem
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - block-list
info:
  title: Block list
  description: ''
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    SignUpDto:
      type: object
      properties:
        email:
          type: string
          example: test@agmail.com
        password:
          type: string
          minLength: 8
          pattern: /^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$/
          example: Asf3&msj
      required:
        - email
        - password
    SignInDto:
      type: object
      properties:
        email:
          type: string
          example: test@agmail.com
        password:
          type: string
          minLength: 8
          pattern: /^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$/
          example: Asf3&msj
      required:
        - email
        - password
    GetSessionInfoDto:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
        iat:
          type: string
        exp:
          type: string
      required:
        - id
        - email
        - iat
        - exp
    GetAccountDto:
      type: object
      properties:
        id:
          type: number
        ownerId:
          type: number
        isBlockingEnabled:
          type: boolean
      required:
        - id
        - ownerId
        - isBlockingEnabled
    PatchAccountDto:
      type: object
      properties:
        isBlockingEnabled:
          type: boolean
    BlockItemDto:
      type: object
      properties:
        id:
          type: number
        blockListId:
          type: number
        type:
          type: string
          enum:
            - KeyWord
            - Website
        data:
          type: string
        createdAt:
          format: date-time
          type: string
      required:
        - id
        - blockListId
        - type
        - data
        - createdAt
    BlockListDto:
      type: object
      properties:
        id:
          type: number
        ownerId:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/BlockItemDto'
      required:
        - id
        - ownerId
        - items
    AddBlockItemDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - KeyWord
            - Website
        data:
          type: string
      required:
        - type
        - data
